blank_issues_enabled: true
contact_links:
    - name: Ask a question
      url: https://github.com/microsoft/react-native-windows/discussions
      about: Haven't found a bug, but still need some help?
